### ISSUE TITLE
Not published to npm registry yet?

### ISSUE THREAD

**Issue by we11adam** [robertklep/qbittorrent#1]
This lib looks very promising. Thanks for the effort!

Would love to see it on npm.

**Comment by robertklep** [comment]
Hah no it's not published yet because I haven't fully tested it (and can't be bothered to, to be honest 😅).

But I've been using it for a personal project for a few months now and it's been working just fine. Feel free to test it out, if it works well enough I'll consider publishing it properly.

**Comment by we11adam** [comment]
well, i understand your point of view. 

i've utilized this lib in one of my personal projects, too, although `client.torrents.add` is the only method i'm using right now but it does what it does.  thanks!

actually i strongly advice that you publish it for more attention so that this lib can get more help. anyway i respect your final personal decision. :-)

**Comment by robertklep** [comment]
I went ahead and published it: https://www.npmjs.com/package/@robertklep/qbittorrent 😊

**Comment by we11adam** [comment]
@robertklep Thanks! That's awesome! ;)
