### ISSUE TITLE
Username and Password never used!

### ISSUE THREAD

**Issue by Zamion101** [robertklep/qbittorrent#2]
While creating `qBitTorrentClient` constructor asks for `url`, `username` and `password` but `username` and `password` is never used in code. Especially in `this.auth.login()` method needs to use those in order to login qBitTorrent Web UI API. I assume Author only tested within localhost and `Bypass authentication for clients on localhost` toggled on.

**Comment by robertklep** [comment]
Yes, your assumption is entirely correct 😬

A bit silly that I never actually implemented this. I'll update the code ASAP.

**Comment by robertklep** [comment]
Fixed in [`@robertklep/qbittorrent@1.0.1`](https://www.npmjs.com/package/@robertklep/qbittorrent).
